// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: evaluations.sql

package db

import (
	"context"
)

const listEvaluationsByStatus = `-- name: ListEvaluationsByStatus :many
SELECT id, tenant_id, user_id, prompt_base, status, idempotency_key, error_message, retry_count, created_at FROM evaluations
WHERE tenant_id = ?
  AND user_id = ?
  AND status IN (?, ?)
ORDER BY created_at DESC
`

type ListEvaluationsByStatusParams struct {
	TenantID string `json:"tenant_id"`
	UserID   int64  `json:"user_id"`
	Status   string `json:"status"`
	Status_2 string `json:"status_2"`
}

func (q *Queries) ListEvaluationsByStatus(ctx context.Context, arg ListEvaluationsByStatusParams) ([]Evaluation, error) {
	rows, err := q.db.QueryContext(ctx, listEvaluationsByStatus,
		arg.TenantID,
		arg.UserID,
		arg.Status,
		arg.Status_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Evaluation
	for rows.Next() {
		var i Evaluation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.PromptBase,
			&i.Status,
			&i.IdempotencyKey,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
